### ISSUE TITLE
HW1 Feedback

### ISSUE THREAD

**Issue by ntjames** [adeniro21/Machine-Learning-I-DeNiro-Anthony#1]
Hi @adeniro21,

All of your code looks correct for HW1, but I wasn't able to see your plots. Can you push the two figures to your repo so they are visible in the .md file? Once they are uploaded, I'll mark this assignment down as a pass

**Comment by adeniro21** [comment]
Hi Nathan, 

I have pushed the figures to the Homework1 folder, within the Homework1_files/figures-markdown_github directory. My apologies, I didn't realize the plots would not be visible.

Thanks,

Anthony DeNiro

**Comment by ntjames** [comment]
Looks good. I've marked this down as a pass
